version 17
clear all
set more off

* Reproduce Table 1: baseline balance table.
*
* Input:
*   data/analysis/baseline_balance_sample.csv
*
* This is an independent Stata cross-check of the R table-generation script.
* It reconstructs the five baseline covariates from the same de-identified raw
* fields and reports T1-Control and T2-Control differences.
*
* Outputs:
*   output/tables/table1_balance_stata.tex
*   output/logs/table1_balance_stata_matrix.csv
*
* Run from the replication_package folder:
*   stata -b do code/stata/01_table1_balance.do

local root "`c(pwd)'"
local data "`root'/data/analysis/baseline_balance_sample.csv"
local out_tables "`root'/output/tables"
local out_logs "`root'/output/logs"

capture mkdir "`root'/output"
capture mkdir "`out_tables'"
capture mkdir "`out_logs'"

import delimited using "`data'", clear varnames(1) stringcols(_all)

* Convert survey fields stored as strings. "n/a" and other nonnumeric values
* become Stata missing values.
destring q14 q17 q19 q54a q58a q62a q69 clusterID, replace force

rename treat treatment
rename clusterID village

foreach v in q54a q58a q62a {
    replace `v' = . if `v' >= 100
}

* Land size mostly follows sampling/sample_frame.R: sum three land components,
* remove implausible totals above 50 acres, and convert acres to hectares. We
* make one correction relative to the original script: if all three land
* components are missing, land size is set to missing rather than zero.
egen land_component_count = rownonmiss(q54a q58a q62a)
egen land_size = rowtotal(q54a q58a q62a)
replace land_size = . if land_component_count == 0
replace land_size = . if land_size > 50
gen land_size_ha = land_size / 2.471

replace q19 = . if q19 > 15

replace q17 = . if q17 == 999
replace q14 = . if q14 == 999
gen age_head = cond(missing(q17), q14, q17)

* Household-head sex uses the reported household-head sex where available and
* respondent sex otherwise.
gen q16_male = .
replace q16_male = 1 if q16 == "Male"
replace q16_male = 0 if q16 == "Female"

gen q13_male = .
replace q13_male = 1 if q13 == "Male"
replace q13_male = 0 if q13 == "Female"

gen male_head = cond(missing(q16_male), q13_male, q16_male)
gen HH_size = q19
gen poor = q69 == 4 | q69 == 5
replace poor = . if missing(q69)

* Additive indicators are kept for the original pairwise joint tests. Mutually
* exclusive arm indicators are used for the displayed treatment-control
* contrasts.
gen treatment1 = treatment == "T1" | treatment == "T2"
gen treatment2 = treatment == "T2"
gen t1_arm = treatment == "T1"
gen t2_arm = treatment == "T2"

tempname B
matrix `B' = J(8, 9, .)

local vars age_head male_head HH_size land_size_ha poor
local i = 1
foreach y of local vars {
    quietly summarize `y' if treatment == "C"
    matrix `B'[`i', 1] = round(r(mean), .001)
    matrix `B'[`i', 2] = round(r(sd), .001)

    quietly regress `y' t1_arm t2_arm, vce(cluster village)
    matrix `B'[`i', 3] = round(_b[t1_arm], .001)
    matrix `B'[`i', 4] = round(_se[t1_arm], .001)
    matrix `B'[`i', 5] = 2 * ttail(e(df_r), abs(_b[t1_arm] / _se[t1_arm]))
    matrix `B'[`i', 6] = round(_b[t2_arm], .001)
    matrix `B'[`i', 7] = round(_se[t2_arm], .001)
    matrix `B'[`i', 8] = 2 * ttail(e(df_r), abs(_b[t2_arm] / _se[t2_arm]))
    matrix `B'[`i', 9] = e(N)

    local ++i
}

* Joint tests. These are Stata equivalents, not exact matches to the R
* implementation where individual-variable SEs use clubSandwich CR3/Satterthwaite.
mlogit treatment age_head male_head HH_size land_size_ha poor, baseoutcome("C")
test age_head male_head HH_size land_size_ha poor
matrix `B'[6, 1] = round(r(chi2), .001)
matrix `B'[6, 2] = round(r(p), .001)

regress treatment1 age_head male_head HH_size land_size_ha poor if inlist(treatment, "T1", "C")
test age_head male_head HH_size land_size_ha poor
matrix `B'[7, 1] = round(r(F), .001)
matrix `B'[7, 2] = round(r(p), .001)

regress treatment2 age_head male_head HH_size land_size_ha poor if inlist(treatment, "T1", "T2")
test age_head male_head HH_size land_size_ha poor
matrix `B'[8, 1] = round(r(F), .001)
matrix `B'[8, 2] = round(r(p), .001)

clear
svmat double `B', names(col)
rename c1 control_mean
rename c2 control_sd
rename c3 t1_minus_control
rename c4 se_t1_minus_control
rename c5 p_t1_minus_control
rename c6 t2_minus_control
rename c7 se_t2_minus_control
rename c8 p_t2_minus_control
rename c9 n

gen row = _n
order row
export delimited using "`out_logs'/table1_balance_stata_matrix.csv", replace

file open tex using "`out_tables'/table1_balance_stata.tex", write replace
file write tex "% Generated by replication_package/code/stata/01_table1_balance.do" _n
file write tex "\begin{tabular}{lcccc}" _n
file write tex "\hline\hline" _n
file write tex " & Control mean & T1 - Control & T2 - Control & N \\" _n
file write tex "\cline{2-5}" _n

local label1 "Household head age (years)"
local label2 "Household head is male (1=yes)"
local label3 "Household size (number)"
local label4 "Land area (ha)"
local label5 "Had difficulties feeding family in last year (1=yes)"

forvalues r = 1/5 {
    local label "`label`r''"
    file write tex "`label' & " %4.3f (control_mean[`r']) " & " %4.3f (t1_minus_control[`r']) " & " %4.3f (t2_minus_control[`r']) " & " %9.0f (n[`r']) " \\" _n
    file write tex " & (" %4.3f (control_sd[`r']) ") & (" %4.3f (se_t1_minus_control[`r']) ") & (" %4.3f (se_t2_minus_control[`r']) ") & \\" _n
}

file write tex "\hline" _n
file write tex "Multinomial test (p-value) & " %4.3f (control_mean[6]) " & (" %4.3f (control_sd[6]) ") & & \\" _n
file write tex "F-test C/T1 (p-value) & " %4.3f (control_mean[7]) " & (" %4.3f (control_sd[7]) ") & & \\" _n
file write tex "F-test T1/T2 (p-value) & " %4.3f (control_mean[8]) " & (" %4.3f (control_sd[8]) ") & & \\" _n
file write tex "\hline\hline" _n
file write tex "\end{tabular}" _n
file close tex
