version 17
clear all
set more off

* Reproduce the differential-attrition-by-stage table from the public inputs.
*
* Inputs:
*   data/analysis/baseline_balance_sample.csv
*   ../endline/data/public/clear_merged_data.csv
*
* Outputs:
*   output/tables/attrition_stage_regressions_stata.tex
*   output/logs/attrition_stage_regressions_stata.csv
*
* Run from the replication_package folder:
*   stata -b do code/stata/04_attrition_diagnostics.do

local root "`c(pwd)'"
local data_baseline "`root'/data/analysis/baseline_balance_sample.csv"
local data_endline "`root'/../endline/data/public/clear_merged_data.csv"
local out_tables "`root'/output/tables"
local out_logs "`root'/output/logs"

capture mkdir "`root'/output"
capture mkdir "`out_tables'"
capture mkdir "`out_logs'"

program define post_stage
    syntax varname, Label(string) Handle(name) N(integer)

    quietly summarize `varlist' if treatment == "C"
    local control_mean = r(mean)

    quietly regress `varlist' t1 t2, vce(cluster village)
    local t1_coef = _b[t1]
    local t1_se = _se[t1]
    local t2_coef = _b[t2]
    local t2_se = _se[t2]

    if missing(`t1_se') | `t1_se' == 0 {
        local t1_p = .
    }
    else {
        local t1_p = 2 * ttail(e(df_r), abs(`t1_coef' / `t1_se'))
    }

    if missing(`t2_se') | `t2_se' == 0 {
        local t2_p = .
    }
    else {
        local t2_p = 2 * ttail(e(df_r), abs(`t2_coef' / `t2_se'))
    }

    quietly test t1 = t2
    local p_equal = r(p)

    post `handle' ("`label'") (`control_mean') (`t1_coef') (`t1_se') (`t1_p') ///
        (`t2_coef') (`t2_se') (`t2_p') (`p_equal') (`n')
end

tempfile baseline_ids baseline_full endline_master results

import delimited using "`data_baseline'", clear varnames(1) stringcols(_all)
rename farmer_ID farmer_id
rename treat treatment
rename clusterID village
quietly isid farmer_id
if _rc {
    di as error "baseline_balance_sample.csv does not have unique farmer_id values."
    exit 459
}
keep farmer_id treatment village
save "`baseline_ids'", replace
save "`baseline_full'", replace

import delimited using "`data_endline'", clear varnames(1) stringcols(_all)
merge m:1 farmer_id using "`baseline_ids'", keep(match) nogen
duplicates tag farmer_id, gen(endline_dup)
count if endline_dup > 0
if r(N) > 0 {
    di as error "Duplicate farmer_id values found in clear_merged_data.csv for sampled households."
    exit 459
}
keep farmer_id q4a checkq9 Merging_Recommendation
save "`endline_master'", replace

use "`baseline_full'", clear
merge 1:1 farmer_id using "`endline_master'", keep(master match) nogen

replace treatment = strtrim(treatment)
destring village, replace force

gen byte t1 = treatment == "T1"
gen byte t2 = treatment == "T2"

* Survey-stage indicators on the full sampled baseline frame.
gen byte endline_target = q4a != ""
gen byte found = q4a == "1"
gen byte interview_completed = checkq9 == "Yes"
gen byte matched_soil = Merging_Recommendation == "Matched (3)"

local sample_n = _N

tempname handle
postfile `handle' str40 stage double control_mean t1_coef t1_se t1_p ///
    t2_coef t2_se t2_p p_equal n using "`results'", replace

post_stage endline_target, label("Endline target") handle(`handle') n(`sample_n')
post_stage found, label("Found") handle(`handle') n(`sample_n')
post_stage interview_completed, label("Interview completed") handle(`handle') n(`sample_n')
post_stage matched_soil, label("Matched to soil test data") handle(`handle') n(`sample_n')

postclose `handle'

use "`results'", clear
export delimited using "`out_logs'/attrition_stage_regressions_stata.csv", replace

gen str16 control_mean_fmt = cond(missing(control_mean), "", ///
    strtrim(string(cond(abs(control_mean) < 0.0005, 0, control_mean), "%9.3f")))
gen str16 t1_coef_fmt = cond(missing(t1_coef), "", ///
    strtrim(string(cond(abs(t1_coef) < 0.0005, 0, t1_coef), "%9.3f")))
gen str16 t2_coef_fmt = cond(missing(t2_coef), "", ///
    strtrim(string(cond(abs(t2_coef) < 0.0005, 0, t2_coef), "%9.3f")))
gen str16 t1_se_fmt = cond(missing(t1_se), "", ///
    strtrim(string(cond(abs(t1_se) < 0.0005, 0, t1_se), "%9.3f")))
gen str16 t2_se_fmt = cond(missing(t2_se), "", ///
    strtrim(string(cond(abs(t2_se) < 0.0005, 0, t2_se), "%9.3f")))
gen str16 p_equal_fmt = cond(missing(p_equal), "", ///
    strtrim(string(cond(abs(p_equal) < 0.0005, 0, p_equal), "%9.3f")))
gen str16 n_fmt = cond(missing(n), "", strtrim(string(n, "%9.0f")))

file open tex using "`out_tables'/attrition_stage_regressions_stata.tex", write replace
file write tex "% Generated by replication_package/code/stata/04_attrition_diagnostics.do" _n
file write tex "\begin{tabular}{lrrrrr}" _n
file write tex "\hline" _n
file write tex "Stage & Control mean & T1 - Control & T2 - Control & p-value: T1 = T2 & N \\" _n
file write tex "\hline" _n

forvalues i = 1/`=_N' {
    local label `"`=stage[`i']''"'
    local control `"`=control_mean_fmt[`i']''"'
    local t1coef `"`=t1_coef_fmt[`i']''"'
    local t2coef `"`=t2_coef_fmt[`i']''"'
    local pequal `"`=p_equal_fmt[`i']''"'
    local nval `"`=n_fmt[`i']''"'
    local t1se `"`=t1_se_fmt[`i']''"'
    local t2se `"`=t2_se_fmt[`i']''"'

    file write tex "`label' & `control' & `t1coef' & `t2coef' & `pequal' & `nval' \\" _n
    file write tex " &  & (`t1se') & (`t2se') &  &  \\" _n
}

file write tex "\hline" _n
file write tex "\end{tabular}" _n
file close tex
