version 17
clear all
set more off

* Reproduce the treatment-fidelity / first-stage table from the public endline.
*
* Input:
*   ../endline/data/public/clear_merged_data.csv
*
* Outputs:
*   output/tables/table_first_stage_stata.tex
*   output/logs/table_first_stage_stata.csv
*   output/logs/table_first_stage_conditional_stats_stata.csv
*
* Run from the replication_package folder:
*   stata -b do code/stata/05_table_first_stage.do

local root "`c(pwd)'"
local data_endline "`root'/../endline/data/public/clear_merged_data.csv"
local out_tables "`root'/output/tables"
local out_logs "`root'/output/logs"

capture mkdir "`root'/output"
capture mkdir "`out_tables'"
capture mkdir "`out_logs'"

program define post_outcome
    syntax varname, Label(string) Handle(name) N(integer)

    quietly summarize `varlist' if treatment == "C"
    local control_mean = r(mean)

    quietly regress `varlist' t1 t2, vce(cluster village)
    local t1_coef = _b[t1]
    local t1_se = _se[t1]
    local t2_coef = _b[t2]
    local t2_se = _se[t2]

    if missing(`t1_se') | `t1_se' == 0 {
        local t1_p = .
    }
    else {
        local t1_p = 2 * ttail(e(df_r), abs(`t1_coef' / `t1_se'))
    }

    if missing(`t2_se') | `t2_se' == 0 {
        local t2_p = .
    }
    else {
        local t2_p = 2 * ttail(e(df_r), abs(`t2_coef' / `t2_se'))
    }

    quietly test t1 = t2
    local p_equal = r(p)

    post `handle' ("`label'") (`control_mean') (`t1_coef') (`t1_se') (`t1_p') ///
        (`t2_coef') (`t2_se') (`t2_p') (`p_equal') (`n')
end

tempfile results conditional_stats

import delimited using "`data_endline'", clear varnames(1) stringcols(_all)
keep if inlist(treat, "C", "T1", "T2") & checkq9 == "Yes"

count if missing(cluster_id_num) | cluster_id_num == ""
if r(N) > 0 {
    di as error "cluster_id_num contains missing values in the interviewed sample."
    exit 459
}

rename treat treatment
rename cluster_id_num village
destring village, replace force

gen byte t1 = treatment == "T1"
gen byte t2 = treatment == "T2"

gen byte received_recommendation = get_rec == "Yes"
gen byte received_and_easy = get_rec == "Yes" & ///
    inlist(ease_rec, "Easy to understand", "Very easy to understand")
gen byte received_and_followed = get_rec == "Yes" & folll_rec == "Yes"
gen byte agronaut_visited = agro_vis == "Yes"
gen byte received_voucher = got_voucher == "Yes"
gen byte redeemed_voucher = redeem == "Yes"
gen byte voucher_enough = vou_en == "Yes"

local sample_n = _N

tempname handle
postfile `handle' str70 outcome double control_mean t1_coef t1_se t1_p ///
    t2_coef t2_se t2_p p_equal n using "`results'", replace

post_outcome received_recommendation, ///
    label("Received recommendation") handle(`handle') n(`sample_n')
post_outcome received_and_easy, ///
    label("Received recommendation and found it easy/very easy") handle(`handle') n(`sample_n')
post_outcome received_and_followed, ///
    label("Received recommendation and followed it") handle(`handle') n(`sample_n')
post_outcome agronaut_visited, ///
    label("Agronaut visited household") handle(`handle') n(`sample_n')
post_outcome received_voucher, ///
    label("Received voucher") handle(`handle') n(`sample_n')
post_outcome redeemed_voucher, ///
    label("Redeemed voucher") handle(`handle') n(`sample_n')
post_outcome voucher_enough, ///
    label("Voucher enough for full recommended purchase") handle(`handle') n(`sample_n')

postclose `handle'

use "`results'", clear
export delimited using "`out_logs'/table_first_stage_stata.csv", replace

gen str16 control_mean_fmt = cond(missing(control_mean), "", ///
    strtrim(string(cond(abs(control_mean) < 0.0005, 0, control_mean), "%9.3f")))
gen str16 t1_coef_fmt = cond(missing(t1_coef), "", ///
    strtrim(string(cond(abs(t1_coef) < 0.0005, 0, t1_coef), "%9.3f")))
gen str16 t2_coef_fmt = cond(missing(t2_coef), "", ///
    strtrim(string(cond(abs(t2_coef) < 0.0005, 0, t2_coef), "%9.3f")))
gen str16 t1_se_fmt = cond(missing(t1_se), "", ///
    strtrim(string(cond(abs(t1_se) < 0.0005, 0, t1_se), "%9.3f")))
gen str16 t2_se_fmt = cond(missing(t2_se), "", ///
    strtrim(string(cond(abs(t2_se) < 0.0005, 0, t2_se), "%9.3f")))
gen str16 p_equal_fmt = cond(missing(p_equal), "", ///
    strtrim(string(cond(abs(p_equal) < 0.0005, 0, p_equal), "%9.3f")))
gen str16 n_fmt = cond(missing(n), "", strtrim(string(n, "%9.0f")))

file open tex using "`out_tables'/table_first_stage_stata.tex", write replace
file write tex "% Generated by replication_package/code/stata/05_table_first_stage.do" _n
file write tex "\begin{tabular}{lrrrrr}" _n
file write tex "\hline" _n
file write tex "Outcome & Control mean & T1 - Control & T2 - Control & p-value: T1 = T2 & N \\" _n
file write tex "\hline" _n

forvalues i = 1/`=_N' {
    local label `"`=outcome[`i']''"'
    local control `"`=control_mean_fmt[`i']''"'
    local t1coef `"`=t1_coef_fmt[`i']''"'
    local t2coef `"`=t2_coef_fmt[`i']''"'
    local pequal `"`=p_equal_fmt[`i']''"'
    local nval `"`=n_fmt[`i']''"'
    local t1se `"`=t1_se_fmt[`i']''"'
    local t2se `"`=t2_se_fmt[`i']''"'

    file write tex "`label' & `control' & `t1coef' & `t2coef' & `pequal' & `nval' \\" _n
    file write tex " &  & (`t1se') & (`t2se') &  &  \\" _n
}

file write tex "\hline" _n
file write tex "\end{tabular}" _n
file close tex

import delimited using "`data_endline'", clear varnames(1) stringcols(_all)
keep if inlist(treat, "C", "T1", "T2") & checkq9 == "Yes"

gen byte received_and_easy = get_rec == "Yes" & ///
    inlist(ease_rec, "Easy to understand", "Very easy to understand")
gen byte received_and_followed = get_rec == "Yes" & folll_rec == "Yes"
gen byte redeemed_voucher = redeem == "Yes"
gen byte voucher_enough = vou_en == "Yes"

tempname handle_conditional
postfile `handle_conditional' str40 metric double value using "`conditional_stats'", replace
quietly summarize received_and_easy if treat == "T1" & get_rec == "Yes"
post `handle_conditional' ("easy_given_received_T1") (r(mean))
quietly summarize received_and_easy if treat == "T2" & get_rec == "Yes"
post `handle_conditional' ("easy_given_received_T2") (r(mean))
quietly summarize received_and_followed if treat == "T1" & get_rec == "Yes"
post `handle_conditional' ("followed_given_received_T1") (r(mean))
quietly summarize received_and_followed if treat == "T2" & get_rec == "Yes"
post `handle_conditional' ("followed_given_received_T2") (r(mean))
quietly summarize redeemed_voucher if treat == "T2" & got_voucher == "Yes"
post `handle_conditional' ("redeemed_given_voucher_T2") (r(mean))
quietly summarize voucher_enough if treat == "T2" & redeem == "Yes"
post `handle_conditional' ("voucher_enough_given_redeemed_T2") (r(mean))
postclose `handle_conditional'

use "`conditional_stats'", clear
export delimited using "`out_logs'/table_first_stage_conditional_stats_stata.csv", replace
